### ISSUE TITLE
Error while running ansible.yml

### ISSUE THREAD

**Issue by harithadamarla** [airavata-courses/alpha#10]
Got the below error when I have run the ansible file for the first time.
![issue1](https://user-images.githubusercontent.com/18641976/45955524-2b9aa480-bfde-11e8-9fe5-aaefa7c34f8a.png)

Probably do you need to add an additional instruction?

**Comment by siddharthpathak** [comment]
If you are using Python 3, then pip comes installed with it. We recommend using python3, and have updated the wiki accordingly. 
For installing python3 run `brew install python3`.
