### ISSUE TITLE
Stock Microservice is up, but not other services

### ISSUE THREAD

**Issue by harithadamarla** [airavata-courses/alpha#11]
Hi Team,
Once I have run the ansible.yml file, I could see that stocks are getting updated periodically, but not news/weather. (A Loading message is getting displayed)

![issue2](https://user-images.githubusercontent.com/18641976/45955912-2ab64280-bfdf-11e8-84dc-9df9d2cfc650.png)

Let me know if I am missing something ?

**Comment by aishwaryadhage** [comment]
Hello,
Have you added weather_api_key and news_api_key in bash file? You will have to change weather_api_key and news_api_key to see the news and weather updates.
Steps are mentioned in the wiki page.
Let us know if that does not work.

**Comment by siddharthpathak** [comment]
Removed the comment as it contained the API key. @harithadamarla were you able to run the application after adding both the weather and news API key?
