### ISSUE TITLE
How are you pulling up the stock price

### ISSUE THREAD

**Issue by harithadamarla** [airavata-courses/alpha#12]
Just curious on how you are trying to update the stock price. If you are using an API to pull it up, is it valid to update the architecture diagram accordingly to represent from where the values are showing up?

Are you gonna include user preferences in this microservice too later on ?

**Comment by siddharthpathak** [comment]
We are not pulling the values from any API, but are generating random values for stock prices every second, and sending the data on a socket. Eventually we will be using real data. 

Yes, adding user preferences is one of our top priorities. The DB service, and schema is ready but we couldn't integrate, and test it before the first release date. It will be integrated in the next release!

**Comment by harithadamarla** [comment]
Cool. Thanks.
