### ISSUE TITLE
Peer Review - Flask version conflict with Python

### ISSUE THREAD

**Issue by karanrk** [airavata-courses/alpha#15]
Hello Team,

1.Nice to see ansible set up for MAC users (Looks like it is high time to buy MAC soon) :)

2. Since i don't own a mac, I tried to start the News microservice implemented in python with Flask.
To give a background of the issue I am running into, I have latest Flask already installed on my machine, but looks like my system is not allowing me to install the flask version that you specified in the requirements.txt file. ( pip2 works just fine, but not pip3) also when i start the flask server, i get no module named flask error.  

Best Regards,
Karan

**Comment by karanrk** [comment]
Figured that out thanks, your virtual env activation step must be before pip install requirements.txt. Step 5 must be after step 2 on the News microservice Wiki page.

The mvn package clean step fails in test1GetDataFromThirdParty, i am guessing it is because we have not provided valid API_KEY.

**Comment by siddharthpathak** [comment]
Fixed the step order in wiki. Thanks for finding it out. 

You can get the keys from [news](https://newsapi.org/) and [weather](https://openweathermap.org/api)

**Comment by hardikrakholiya** [comment]
@karanrk let me know if you need any help. Else if this is resolved please close the issue.

**Comment by karanrk** [comment]
Tried with valid API_keys and works fine.Good job guys.
