### ISSUE TITLE
Suggestions on Napkin Diagram 

### ISSUE THREAD

**Issue by karanrk** [airavata-courses/alpha#16]
Hello Team,

Small suggestion on your Napkin diagram

1. It is more technical than needed (think of it this way - if i am not a computer guy and just an Investor with $ but no technical knowledge, i must be able to understand your application/business idea)

2. To advocate the above point, your architecture diagram is just perfect but both your napkin diagram and architecture diagram almost look similar.

**Comment by hardikrakholiya** [comment]
@karanrk thank you. we will consider your suggestion and would change the napkin diagram accordingly.

**Comment by aishwaryadhage** [comment]
@karanrk , thanks for the suggestion. I have updated Napkin Diagram and closing this issue.[a171b87](url)
