### ISSUE TITLE
API keys Required

### ISSUE THREAD

**Issue by pswargam** [airavata-courses/alpha#17]
Hi Team,

I think I will need the weather API and News API key.

Thanks 
Prashanth

**Comment by siddharthpathak** [comment]
Hey, you can get the keys from [news](https://newsapi.org/) and [weather](https://openweathermap.org/api)

**Comment by pswargam** [comment]
Hi Team,

I was able to run the application. Stock values, News and weather are visible on API.

Thanks
Prashanth

**Comment by hardikrakholiya** [comment]
@pswargam if resolved, can you please close this issue?

**Comment by pswargam** [comment]
Sure
