### ISSUE TITLE
Peer review -- Service Discovery -- IP 's visible

### ISSUE THREAD

**Issue by pswargam** [airavata-courses/alpha#26]
Hi team,

I see ip's in the code. I think you can complete the service discovery part

thanks
Prashanth

**Comment by siddharthpathak** [comment]
Looking into service discovery using Zookeeper or Docker Swarm.

**Comment by hardikrakholiya** [comment]
Service discovery server for registering and getting service instances has been completed. All non-Java instances would register to ZK using this service.
