### ISSUE TITLE
Peer Review for project 2 

### ISSUE THREAD

**Issue by karanrk** [airavata-courses/alpha#34]
* Good job with architecture diagram, clearly explains the use cases for Kafka and its implementation
* Tried live demo with url given on the wiki page, all works fine - curious to know, how frequently are you guys updating the topic, because the stock updates too frequently (every second or so)
* Also please let us know, if you guys have implemented service discovery, i know for a fact you were trying docker swarm.
* For the CI/CD - can i build now and test the pipeline?

**Comment by karanrk** [comment]
Manually triggered the build and tested out the pipeline, works fine.

I had a question - suppose If you were to push/edit a single line of code to any one microservice, with your current configuration it would build all the microservices and re-deploy all the microservices again which might impact the downtime for the whole application. You could build each microservice separately and deploy them separately. In this way you could keep the application live and only redeploy individual microservice.

**Comment by aishwaryadhage** [comment]
We were earlier building it in a single jenkinsfile. Thanks for the suggestion, we updated jenkinsfile to build and deploy each microservice separately.
