### ISSUE TITLE
PeerReview for MileStone 3

### ISSUE THREAD

**Issue by harithadamarla** [airavata-courses/alpha#41]
I couldn't find the documentation for milestone3. Can you please update the wiki

**Comment by hardikrakholiya** [comment]
yes we are in the process of generating statistics and plots. We will update soon.

**Comment by hardikrakholiya** [comment]
Please find the documentation related to the milestone 3 [here](https://github.com/airavata-courses/alpha/wiki/Perfomance-Metrics). Please try to overload the server with as many requests as you can send. We tried overloading using 2 systems(with maximum load possible) but failed to break it. You can try as well. `http://149.165.169.102:8080/` is the URL.

**Comment by harithadamarla** [comment]
Interesting approach of having multiple load balancer entries. I am interested in your future implementation of having multiple database servers and maintaining state between them.

**Comment by harithadamarla** [comment]
Good to see the application not crashing even after so many requests. I was wondering if the third party API calls you have in your application don't have any request limit per day.

**Comment by hardikrakholiya** [comment]
It does have limits per day/minute. After some number of requests it was rejecting our calls so we had to mask the exceptions raised in the process. But even in the case of failures the latency of calling 3rd party API will still be there so our statistics are still accurate. In 4th milestone we are planning to remove 3rd party dependencies and introduce separate database for each microservice to make it even faster (#42). Stay tuned.
