### ISSUE TITLE
Peer Review Project 4

### ISSUE THREAD

**Issue by harithadamarla** [airavata-courses/alpha#63]
Hi Team,

The application has a great improvement in UI. I have checked your Jenkins configuration for ms-stocks branch. I could see that deployments are getting deleted followed by sleep for 20ms. Are you not experiencing a downtime after every code push ? Also, the credentials are not hidden which may not be a good practice.

**Comment by harithadamarla** [comment]
Even after clicking logout I believe session is not getting killed. I am directly able to access http://149.165.157.60:30005/App without logging in.

**Comment by harithadamarla** [comment]
Great job on System architecture and kubernetes dashboard, clearly depicting the system functionality and flow.

**Comment by aishwaryadhage** [comment]
Hello Haritha,
Thanks for pointing out about the logout issue and credentials. The issue has been fixed, can you please check and let me know if there are any further issues.

**Comment by harithadamarla** [comment]
> Hello Haritha,
> Thanks for pointing out about the logout issue and credentials. The issue has been fixed, can you please check and let me know if there are any further issues.

Hi Aishwarya,

Thanks. Could see that issue is fixed.

**Comment by hardikrakholiya** [comment]
Closing this issue now.
