### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by pswargam** [airavata-courses/alpha#9]
Hi Team Alpha,

I am assigned to review your project. I am using a Mac. I am having python 3.6 version. Does your project require any specific version of python?

Thanks
Prashanth

**Comment by aishwaryadhage** [comment]
It should work with python 3.6 version

**Comment by pswargam** [comment]
It works .

Thanks

**Comment by pswargam** [comment]
All the api's are working fine. The ui shows stocks, weather and news.

Thanks
Prashanth
